name: Build and Deploy Workflow

on:
  push:
    branches:
      - main  # Trigger this workflow on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH for Git access
      - name: Setup SSH for Git
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.STAGINGENV }}  # SSH private key stored in GitHub secrets

      # Step 3: Pull the latest code
      - name: Pull latest changes
        run: git pull --force

      # Step 4: Navigate to tw-block and install dependencies
      - name: Build tw-block plugin
        run: |
          cd wp-content/plugins/tw-block
          npm ci  # Clean install dependencies
          npm run build

      # Step 5: Navigate to TechWishWebsite and install dependencies
      - name: Build TechWishWebsite
        run: |
          cd TechWishWebsite
          npm ci  # Clean install dependencies
           echo "Current directory: $(pwd)"
          echo "Listing all files in the directory, including hidden ones:"
          ls -lha  # Include hidden files and detailed view

          # Check and update .env file contents
          if [ -f .env ]; then
            echo ".env file exists. Checking its content..."
            if grep -q 'WP_URL="http://tw.local"' .env; then
              echo "Replacing local URL with staging URL in .env file."
              sed -i 's|WP_URL="http://tw.local"|WP_URL="https://stagingenv.techwish.com"|g' .env
            elif ! grep -q 'WP_URL="https://stagingenv.techwish.com"' .env; then
              echo "Adding staging URL to .env file."
              echo 'WP_URL="https://stagingenv.techwish.com"' >> .env
            else
              echo ".env file already contains the correct staging URL."
            fi
          else
            echo ".env file does not exist. Creating a new one with the staging URL."
            echo 'WP_URL="https://stagingenv.techwish.com"' > .env
          fi

          # Debugging: Display .env contents
          echo "Contents of .env file after update:"
          cat .env          
          npm run build
